version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db-compose
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_E_COMMERCE_USER: ${MONGODB_E_COMMERCE_USER}
      MONGODB_E_COMMERCE_PASSWORD: ${MONGODB_E_COMMERCE_PASSWORD}
  mongo-express:
    image: mongo-express
    container_name: mongo-express-compose
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db-compose
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
volumes:
  mongo_data:
   driver: local